sudo: enabled
language: cpp
dist: trusty
osx_image: xcode8.3
os:
  - linux
  - osx
services:
  - docker

notifications:
  email: false

before_install:
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
     brew install qt cmake;
     brew link qt --force;
   fi

script:
 - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
     docker run longhanks/qlift-builder;
   fi
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    ./buildscript.sh;
   fi

